# save as configs/imag_default.yaml
project: polar-mm-HOPV

# data
seed: 42
data_file: ../data/HOPV.pt
train_fraction: 0.9
batch_size: 64
normalize: false

# optimisation
epochs: 85
lr: 5.0e-4
weight_decay: 0.0
optimizer: AdamW

# model (arguments forwarded to DetaNet)
cutoff: 3.0
num_block: 6
num_features: 256
scalar_outsize: 248   # 4*62
attention_heads: 8
irreps_out: 124x2e
out_type: cal_multi_tensor
finetune: False
finetune_file: "/home/maria/dyn-detanet/code/trained_param/471_vibrant-sweep_polar_Falsenormalize_70epochs_32bs_0.0007335013870127138lr_6blocks_256features_onlyKITqm9.pth"

target: y